# Details about the hosted changelog page
title: Hosted Demo-Changelog
subtitle: Check out the latest product updates below.
company: ChangelogHQ
logo: /assets/images/logo.png"

# color configurtion for the theme
colors:   
  body-bg: "#f6f6f7" 
  header-bg: "#4d60f2"
  post-bg: "#fefefe"  

# Build settings
markdown: kramdown

# Settings for SCSS
sass:
  style: compressed 

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# The changelog hq remote theme 
remote_theme: ChangelogHQ/jekyll-theme-changeloghq@v0.0.1

# Default configuration for pagination
paginate: 10
paginate_path: "/posts/:num/"