# Details about the hosted changelog page
title: Your awesome title

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-remote-theme

# The changelog hq remote theme 
remote_theme: ChangelogHQ/jekyll-theme-changeloghq